# SEO settings
title: melissawm
description: "Github page for melissawm"
keywords: "melissawm, math, applied math, programming, python, LaTeX"
url: https://melissawm.github.io
#baseurl: "/"
baseurl: null

#google_analytics: UA-52446115-1
repo: http://github.com/melissawm/melissawm.github.io
#disqus_shortname: "nandothemes"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Melissa Weber Mendonça
  job      : currently working as a Software Engineer
  bio      : "I'm an applied mathematician, free software enthusiast, podcaster and mom. My pronouns are she/her/ela."
  thumb    : /images/melissawm.jpg
  email    : melissawm@gmail.com
  url      : http://melissawm.github.io
  github   : http://github.com/melissawm
  twitter  : http://twitter.com/melissawm
  #facebook : http://facebook.com/fernando.dev
  linkedin : http://linkedin.com/in/axequalsb

# social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: "@melissawm"

plugins:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
